@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluMUBleGFtcGxlLmNvbSIsIm5pY2tuYW1lIjoi6rSA66as7J6QMSIsImlhdCI6MTc0Nzg5MDY1NiwiZXhwIjoxNzQ3ODk0MjU2fQ.nWGkpRg7vHcZbnSUAN7K7q8V_HfjSDtbGXr1SKPZFro

################ 챌린지 ################
### 챌린지 승인
PATCH http://localhost:8080/admin/challenges/34
Content-Type: application/json 
Cookie: accessToken={{accessToken}}

{
	"adminStatus": "ACCEPTED"
}

### 챌린지 거절
PATCH http://localhost:8080/admin/challenges/34
Content-Type: application/json 
Cookie: accessToken={{accessToken}}

{
	"adminStatus": "REJECTED",
	"adminMessage": "독스루는 개발 문서 번역 플랫폼으로, 다른 종류의 번역 챌린지를 개최할 수 없음을 알려드립니다. 감사합니다."
}

### 챌린지 삭제
PATCH http://localhost:8080/admin/challenges/33
Content-Type: application/json 
Cookie: accessToken={{accessToken}}

{
	"adminStatus": "DELETED",
	"adminMessage": "독스루는 개발 문서 번역 플랫폼으로, 폭력성과 관련된 내용을 포함할 수 없음을 안내드립니다. 감사합니다."
}

################ 작업물 - 챌린지 ################
### 작업물 상세 조회
GET http://localhost:8080/challenges/:challengeId/works/:workId
Content-Type: application/json

### 작업물 제출
POST http://localhost:8080/works/challenges/:challengeId/works
Content-Type: application/json


################ 작업물 ################
### 작업물 수정 PATCH /works/:workId

PATCH http://localhost:8080/works/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MjA1ODgsImV4cCI6MTc0NzgyNDE4OH0.M2M1hQh2m5GMm2MEVCGHPWk-k6sbGwOYfcLUR3aLuVk
{
  "content":"작업물 수정 PATCH가 잘 작동해요!"
}

### 작업물 소프트삭제 (작업물 비활성화 필드 true)
PATCH http://localhost:8080/admin/works/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWIwYWlzeXAwMDAwY2NveWFhem1tbzllIiwiZW1haWwiOiJna3NrdGwxMjNAbmF2ZXIuY29tIiwibmlja25hbWUiOiLrgpjripTslbzrqYvsp4TquIjrtpXslrQiLCJpYXQiOjE3NDc5NzY1NzcsImV4cCI6MTc0Nzk4MDE3N30.qQbeTO8fIoT_9kMO_AR92yok-wmONLegexyiZm4OYU4
Content-Type: application/json

{
  "deletionReason": "사용자 요청에 의한 삭제 사유"
}

### 작업물 하드삭제 (작업물 삭제)
DELETE http://localhost:8080/works/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MjA1ODgsImV4cCI6MTc0NzgyNDE4OH0.M2M1hQh2m5GMm2MEVCGHPWk-k6sbGwOYfcLUR3aLuVk
Content-Type: application/json


################ 피드백 ################
### 피드백 목록 조회

GET http://localhost:8080/works/2/feedbacks
Accept: application/json

### 피드백 등록
POST http://localhost:8080/works/2/feedbacks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MDg4NDYsImV4cCI6MTc0NzgxMjQ0Nn0.bSpmeGcmd_XqDoPNFLYgM2Xt0u-6v9rcNBM-qe_rzC8; Max-Age=3600; Path=/; Expires=Wed, 21 May 2025 07:27:26 GMT; HttpOnly; SameSite=None,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MDg4NDYsImV4cCI6MTc0OTAxODQ0Nn0.lrX2V-qvjQpX8etKe7a-m_JnkWgqgKqSztV-cKOWwjA

{
  "content": "이 작업물에 대한 첫 번째 피드백입니다!"
}

### 피드백 수정
PATCH http://localhost:8080/works/2/feedbacks/158
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MDg4NDYsImV4cCI6MTc0NzgxMjQ0Nn0.bSpmeGcmd_XqDoPNFLYgM2Xt0u-6v9rcNBM-qe_rzC8; Max-Age=3600; Path=/; Expires=Wed, 21 May 2025 07:27:26 GMT; HttpOnly; SameSite=None,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MDg4NDYsImV4cCI6MTc0OTAxODQ0Nn0.lrX2V-qvjQpX8etKe7a-m_JnkWgqgKqSztV-cKOWwjA

{
  "content": "수정된 피드백 내용입니다."
}

### 피드백 삭제
DELETE http://localhost:8080/works/2/feedbacks/158
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MDg4NDYsImV4cCI6MTc0NzgxMjQ0Nn0.bSpmeGcmd_XqDoPNFLYgM2Xt0u-6v9rcNBM-qe_rzC8; Max-Age=3600; Path=/; Expires=Wed, 21 May 2025 07:27:26 GMT; HttpOnly; SameSite=None,refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MDg4NDYsImV4cCI6MTc0OTAxODQ0Nn0.lrX2V-qvjQpX8etKe7a-m_JnkWgqgKqSztV-cKOWwjA
