### 작업물 수정 PATCH /works/:workId

PATCH http://localhost:8080/works/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MTY2OTAsImV4cCI6MTc0NzgyMDI5MH0.fqB8IDJJ4iEbWy4vwttJ2T6AnlzSs-PJaZ8EDYhWZ5o

{
  "content":"작업물 수정 PATCH가 잘 작동해요!"
}

### 작업물 삭제 PATCH /admin/works/:workId
### 삭제사유가 전송되도록 PATCH, BODY 추가해야함

PATCH http://localhost:8080/admin/works/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MTY2OTAsImV4cCI6MTc0NzgyMDI5MH0.fqB8IDJJ4iEbWy4vwttJ2T6AnlzSs-PJaZ8EDYhWZ5o
Content-Type: application/json

{
  "deletionReason": "사용자 요청에 의한 삭제 사유"
}