@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbjEiLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsIm5pY2tuYW1lIjoi6rSA66as7J6QIiwiaWF0IjoxNzQ4MzM0MzYyLCJleHAiOjE3NDgzMzc5NjJ9.G6zzs-qeTZq6CXDAhgrzLOKCPHLyUNFnC_vYRDOtLWw

################ 챌린지 ################
### 챌린지 승인
PATCH http://localhost:8080/admin/challenges/20
Content-Type: application/json 
Cookie: accessToken={{accessToken}}

{
	"adminStatus": "ACCEPTED"
}

### 챌린지 거절
PATCH http://localhost:8080/admin/challenges/20
Content-Type: application/json 
Cookie: accessToken={{accessToken}}

{
	"adminStatus": "REJECTED",
	"adminMessage": "독스루는 개발 문서 번역 플랫폼으로, 다른 종류의 번역 챌린지를 개최할 수 없음을 알려드립니다. 감사합니다."
}

### 챌린지 삭제
PATCH http://localhost:8080/admin/challenges/20
Content-Type: application/json 
Cookie: accessToken={{accessToken}}

{
	"adminStatus": "DELETED",
	"adminMessage": "독스루는 개발 문서 번역 플랫폼으로, 폭력성과 관련된 내용을 포함할 수 없음을 안내드립니다. 감사합니다."
}

### 작업물 소프트삭제 (작업물 비활성화 필드 true)
PATCH http://localhost:8080/admin/works/4
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
  "deletionReason": "사용자 요청에 의한 삭제 사유"
}