### 회원가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
    "email" : "user5@test.com",
    "nickname" : "user5",
    "password" : "5555",
    "passwordConfirmation" : "5555"
}

### 로그인
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
    "email" : "user3@test.com",
    "password" : "3333"
}

### 토큰 갱신
POST http://localhost:8080/auth/refresh-token
Cookie: refreshToken={{$processEnv REQUEST_REFRESHTOKEN}}
