@REFRESH_TOKEN =

### 회원가입
POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
    "email" : "user3@test.com",
    "nickname" : "user3",
    "password" : "3333",
    "passwordConfirmation" : "3333"
}

### 로그인
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
    "email" : "user6@test.com",
    "password" : "6666"
}

### 관리자 로그인
POST http://localhost:8080/auth/sign-in
Content-Type: application/json

{
    "email" : "admin1@example.com",
    "password" : "adminpassword1"
}

### 토큰 갱신
POST http://localhost:8080/auth/refresh-token
Cookie: refreshToken={{REFRESH_TOKEN}}

