@ACCESS_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF4N2xobDAwMDAyY2M2Y245N3VrMDR0IiwiZW1haWwiOiJ1c2VyM0B0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjMiLCJpYXQiOjE3NDc4MDUzOTUsImV4cCI6MTc0NzgwODk5NX0.h6pIQAsSACs9F20uk_GgS16EU0taJ8RPFxXkdY1ETlQ

### 챌린지 쿼리 조회
GET http://localhost:8080/challenges?page=1&pageSize=5&category=Modern JS&docType=블로그&keyword=함께

### 챌린지 등록
POST http://localhost:8080/challenges
Content-Type: application/json 
Authorization: Bearer {{ACCESS_TOKEN}}

{
  "title": "챌린지 등록",
  "description": "모두 함께 도전해봅시다",
  "category": "Moder JS",
  "docType": "블로그",
  "originalUrl": "https://test1-url.com",
  "deadline": "2024-11-28T00:30:21.142Z",
  "maxParticipant": 5
}
