@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWIwYWlzeXAwMDAwY2NveWFhem1tbzllIiwiZW1haWwiOiJna3NrdGwxMjNAbmF2ZXIuY29tIiwibmlja25hbWUiOiLrgpjripTslbzrqYvsp4TquIjrtpXslrQiLCJpYXQiOjE3NDgxNzExODMsImV4cCI6MTc0ODE3NDc4M30.6DuHemtAwG_KzSte_UamdzrG1UlbXwYee1PTCUTVm5w

### 유저 정보 조회
GET http://localhost:8080/users/me
Cookie: accessToken={{accessToken}}

### 나의 챌린지 목록 조회 - 참여중
GET http://localhost:8080/users/me/challenges?myChallengeStatus=participated
Cookie: accessToken={{accessToken}}

### 나의 챌린지 목록 조회 - 완료된
GET http://localhost:8080/users/me/challenges?myChallengeStatus=completed
Cookie: accessToken={{accessToken}}

### 나의 챌린지 목록 조회 - 내가 만든 챌린지 (applied로 요청)
GET http://localhost:8080/users/me/challenges?myChallengeStatus=applied
Cookie: accessToken={{accessToken}}

### 키워드 검색 예시 - next 키워드 포함 챌린지
GET http://localhost:8080/users/me/challenges?myChallengeStatus=participated&keyword=next
Cookie: accessToken={{accessToken}}
