@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWIwYWlzeXAwMDAwY2NveWFhem1tbzllIiwiZW1haWwiOiJna3NrdGwxMjNAbmF2ZXIuY29tIiwibmlja25hbWUiOiLrgpjripTslbzrqYvsp4TquIjrtpXslrQiLCJpYXQiOjE3NDgyMTk5NzQsImV4cCI6MTc0ODIyMzU3NH0._4ucfr8w_BsznRhfsXsu0v2TgHIFGF85jGh_h8y-9oU
### 현재 챌린지의 작업물 전체 조회
GET http://localhost:8080/challenges/3/works
Content-Type: application/json
Cookie: accessToken={{accessToken}}

### 작업물 상세 조회
GET http://localhost:8080/challenges/5/works/58
Content-Type: application/json
Cookie: accessToken={{accessToken}}

### 작업물 생성
POST http://localhost:8080/challenges/11/works
Content-Type: application/json
Cookie: accessToken={{accessToken}}

### 작업물 제출 및 수정
PATCH http://localhost:8080/works/54
Content-Type: application/json
Cookie: accessToken={{accessToken}}

{
    "content": "수정된 작업물 내용입니다. 111"
}

### 작업물 삭제 .
DELETE http://localhost:8080/works/56
Cookie: accessToken={{accessToken}}

### 작업물 소프트삭제 (작업물 비활성화 필드 true)
PATCH http://localhost:8080/admin/works/4
Cookie: accessToken={{accessToken}}
Content-Type: application/json

{
  "deletionReason": "사용자 요청에 의한 삭제 사유456"
}

### 작업물 좋아요
POST http://localhost:8080/works/48/like
Content-Type: application/json
Cookie: accessToken={{accessToken}}

### 작업물 좋아요 취소
DELETE http://localhost:8080/works/58/like
Content-Type: application/json
Cookie: accessToken={{accessToken}}
