@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWF3a2R4NDAwMDAwbzg5Nzh5bWJrOXUzIiwiZW1haWwiOiJ1c2VyNEB0ZXN0LmNvbSIsIm5pY2tuYW1lIjoidXNlcjQiLCJpYXQiOjE3NDc4MjY1NTQsImV4cCI6MTc0NzgzMDE1NH0.2RgjFVTHY1H-VApvY7oJGXjhOzfv_kkNzPfUk35_MDI

### 작업물 전체 조회
GET http://localhost:8080/works
Content-Type: application/json

# TODO : 나중에 토큰으로 변경
{
    "userId": "user1"
}

### 작업물 상세 조회
GET http://localhost:8080/challenges/5/works/5
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 작업물 제출
POST http://localhost:8080/challenges/12/works
Content-Type: application/json
Authorization: Bearer {{accessToken}}

// TODO : authorId는 추후 토큰으로 변경

{
    "content": "이것은 챌린지 2의 새로운 작업물입니다.",
    "authorId": "admin1"
}

### 작업물 수정
PATCH http://localhost:8080/works/4
Content-Type: application/json

{
    "content": "수정된 작업물 내용입니다."
}

### 작업물 삭제 .
DELETE http://localhost:8080/works/4


### 작업물 좋아요
POST http://localhost:8080/works/3/like
Content-Type: application/json

# userId는 cuid 형식으로 보내야함
{
    "userId": "cmaw8x85h0000upnw6blr5t3d"
}

### 작업물 좋아요 취소
DELETE http://localhost:8080/works/3/like
Content-Type: application/json

{
    "userId": "cmaw8x85h0000upnw6blr5t3d"
}

